name: Deploy with AWS SAM

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::863388854740:role/GitHubActionsDeployRole
          aws-region: us-east-1

      - name: Install SAM CLI
        run: |
          curl -Lo sam.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
          unzip sam.zip -d sam-install
          sudo ./sam-install/install

      - name: Build and deploy with SAM
        run: |
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name billing-system --capabilities CAPABILITY_IAM